# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Today I Learned"
email: "hello@ramottamado.dev"
author: "Tamado Ramot Sitohang"
description: Today I learned.

nadya:
  date_format: "%b %d, %Y"
  disable_attribution: false
  disable_social: true

defaults:
  - scope:
      path: "_posts"
    values:
      twitter:
        card: summary_large_image

favicon: "favicon.svg"
logo: "favicon.svg"
icon: "favicon.png"
alt_icon: "favicon.ico"

# SEO
google_site_verification: "zaJj36ddah20RkBG1RrQqWm-IlXepNuw8ch6SYXeBPQ"
gravatar: d380135b4724b6b8e74bd9f41b978284
github:
  username: "ramottamado"
# instagram:
#   username: ""
# linkedin:
#   username: "ramottamado"
twitter:
  card: summary
  username: "theramottamado"
facebook:
  publisher: 103250301049786
  author: 100000091609630
social:
  name: "Tamado Ramot Sitohang"
  links:
    - "https://ramottamado.dev"
    - "https://twitter.com/theramottamado"

# Plugin Settings
# sitemap:
#   changefreq: monthly
feed:
  excerpt_only: true

# Jekyll
excerpt_separator: <!--more-->
permalink: /:title/

remote_theme: ramottamado/nadya

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    default_lang: html

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
  - jemoji
